# Generated by Django 4.0.4 on 2022-05-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.IntegerField()),
                ('fechaNac', models.DateField()),
                ('obraSocial', models.CharField(max_length=40)),
                ('afiliado', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
