# Generated by Django 4.0.4 on 2022-06-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.CharField(max_length=40)),
                ('mp', models.IntegerField()),
                ('especialidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Obrasocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('cuit', models.IntegerField()),
            ],
        ),
    ]
